In [1]:
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from curl_cffi import requests

ModuleNotFoundError: No module named 'yfinance'

In [ ]:
lista =[]

with open('stocks.txt', 'r') as file:
    for line in file:
        lista.append(line.strip())

In [ ]:
hoje= datetime.now()
start_date = f'{hoje.year - 5}-01-01'
doze_meses = hoje - timedelta(days=365)
doze_meses= doze_meses.date()

In [ ]:
session = requests.Session(impersonate="chrome")

In [ ]:

resultado = pd.DataFrame(columns=['ticker', 'preço', 'preço-alvo', 'yield', '-1dp','dp', 'potencial', 'recomendação'])

In [ ]:
for stock in lista:
    print(stock)
    ação = yf.Ticker(f'{stock}.SA', session=session)

    historico = ação.history(start=start_date)
    historico['yield'] = historico['Dividends']/historico['Close']
    historico_div = historico[historico['yield'] != 0]

    historico_doze_meses = historico[historico.index >= doze_meses.__str__()]
    yield_doze_meses = historico_doze_meses['yield'].sum()

    dividends_doze_meses = historico_doze_meses['Dividends'].sum()



    agrupado = historico_div.groupby(historico_div.index.year).sum()
    try:
        if agrupado.index[-1] == hoje.year:
            agrupado.iloc[-1, -1] = yield_doze_meses
    except:
        print(agrupado)
    
    media =agrupado['yield'].mean()
    desv=agrupado['yield'].std()

    ticker = stock
    preço = historico.iloc[-1]['Close']
    target_price = dividends_doze_meses/0.06
    dyield = media
    menos_dp = media - desv
    potential = target_price/preço - 1
    
    if potential > 0 and menos_dp >= 0.06 and dyield >= 0.06 and len(agrupado) >= 5:
        recomenda = 'compra'
    elif (menos_dp >= 0.06 and dyield >= 0.06 and potential < 0 and len(agrupado) >= 5) or (dyield >= 0.06 and len(agrupado) >= 5) : 
        recomenda = 'espera'
    else:
        recomenda = 'venda'
        
     
    linha = [ticker, preço, target_price, dyield, menos_dp,desv, potential, recomenda]

    resultado = pd.concat([resultado, pd.DataFrame([linha], columns=resultado.columns)], ignore_index=True)

VALE3
PETR3
BBAS3
BBDC4
ABCB4
ITUB4
SANB11
BMGB4
BRSR6
BEES3
BPAC11
BAZA3
BGIP4
BMEB4
BNBR3
BPAN4
BRBI11
BRIV3
BMIN4
BSLI3
ITSA4
BBSE3
CPFE3
VIVT3
NEOE3
B3SA3
CXSE3
EQTL3
ISAE4
ENGI3
PSSA3
SAPR3
ALUP3
TAEE11
WIZC3

In [ ]:
resultado

,ticker,preço,preço-alvo,yield,-1dp,dp,potencial,recomendação
0,VALE3,57.099998,75.962750,0.120261,0.057701,0.062560,0.330346,espera
1,PETR3,34.230000,87.297567,0.390117,0.033687,0.356430,1.550323,espera
2,BBAS3,22.230000,20.429050,0.079517,0.055366,0.024151,-0.081014,espera
3,BBDC4,16.889999,20.736483,0.066893,0.033532,0.033362,0.227737,espera
4,ABCB4,22.879999,32.433333,0.089394,0.065735,0.023658,0.417541,compra
...,...,...,...,...,...,...,...,...
65,PSSA3,50.160000,31.998117,0.050887,0.031228,0.019659,-0.362079,venda
66,SAPR3,7.690000,6.815950,0.064123,0.040756,0.023367,-0.113661,espera
67,ALUP3,10.670000,4.948717,0.045422,0.029102,0.016320,-0.536203,venda
68,TAEE11,34.889999,49.331633,0.130041,0.094756,0.035285,0.413919,compra
69,WIZC3,8.230000,4.171983,0.077289,0.047389,0.029900,-0.493076,espera

In [ ]:
compras = resultado[resultado['recomendação'] == 'compra']
compras

,ticker,preço,preço-alvo,yield,-1dp,dp,potencial,recomendação
4,ABCB4,22.879999,32.433333,0.089394,0.065735,0.023658,0.417541,compra
6,SANB11,28.830000,29.046550,0.080516,0.062986,0.017530,0.007511,compra
8,BRSR6,11.920000,18.240800,0.092660,0.064526,0.028134,0.530268,compra
11,BAZA3,78.300003,133.537650,0.124642,0.065021,0.059621,0.705462,compra
18,BMIN4,17.490000,23.333333,0.093575,0.065484,0.028091,0.334096,compra
21,BBSE3,32.139999,71.037600,0.108227,0.078922,0.029305,1.210255,compra
33,TAEE11,34.869999,49.331633,0.130041,0.094756,0.035285,0.414730,compra
39,ABCB4,22.840000,32.433333,0.089394,0.065735,0.023658,0.420023,compra
41,SANB11,28.879999,29.046550,0.080516,0.062986,0.017530,0.005767,compra
43,BRSR6,11.930000,18.240800,0.092660,0.064526,0.028134,0.528986,compra
46,BAZA3,78.300003,133.537650,0.124642,0.065021,0.059621,0.705462,compra
53,BMIN4,17.490000,23.333333,0.093575,0.065484,0.028091,0.334096,compra
56,BBSE3,32.200001,71.037600,0.108227,0.078922,0.029305,1.206137,compra
68,TAEE11,34.889999,49.331633,0.130041,0.094756,0.035285,0.413919,compra

In [ ]:
resultado[resultado['recomendação'] == 'venda']

,ticker,preço,preço-alvo,yield,-1dp,dp,potencial,recomendação
5,ITUB4,37.430000,47.841617,0.058947,0.036645,0.022301,0.278162,venda
7,BMGB4,3.810000,5.285467,0.092127,0.070691,0.021435,0.387262,venda
10,BPAC11,45.990002,17.594200,0.025471,0.018792,0.006679,-0.617434,venda
15,BPAN4,8.090000,4.024833,0.034845,0.024479,0.010366,-0.502493,venda
16,BRBI11,17.389999,18.500000,0.077501,0.069247,0.008254,0.063830,venda
17,BRIV3,12.860000,0.000000,0.009656,0.002352,0.007304,-1.000000,venda
19,BSLI3,9.320000,6.882433,0.028737,0.009543,0.019194,-0.261541,venda
22,CPFE3,38.220001,0.000000,0.112538,0.072401,0.040137,-1.000000,venda
24,NEOE3,28.680000,13.801983,0.049376,0.030123,0.019253,-0.518759,venda
25,B3SA3,12.980000,4.922383,0.037306,0.028976,0.008330,-0.620772,venda
27,EQTL3,36.119999,13.154900,0.020899,0.013123,0.007776,-0.635800,venda
29,ENGI3,14.170000,9.666667,0.033179,0.015760,0.017419,-0.317808,venda
30,PSSA3,50.080002,31.998117,0.050887,0.031228,0.019659,-0.361060,venda
32,ALUP3,10.670000,4.948717,0.045422,0.029102,0.016320,-0.536203,venda
40,ITUB4,37.470001,47.841617,0.058947,0.036645,0.022301,0.276798,venda
42,BMGB4,3.800000,5.285467,0.092127,0.070691,0.021435,0.390912,venda
45,BPAC11,45.990002,17.594200,0.025471,0.018792,0.006679,-0.617434,venda
50,BPAN4,8.180000,4.024833,0.034845,0.024479,0.010366,-0.507967,venda
51,BRBI11,17.400000,18.500000,0.077501,0.069247,0.008254,0.063218,venda
52,BRIV3,12.860000,0.000000,0.009656,0.002352,0.007304,-1.000000,venda
54,BSLI3,9.320000,6.882433,0.028737,0.009543,0.019194,-0.261541,venda
57,CPFE3,38.299999,0.000000,0.112538,0.072401,0.040137,-1.000000,venda
59,NEOE3,28.700001,13.801983,0.049376,0.030123,0.019253,-0.519095,venda
60,B3SA3,12.970000,4.922383,0.037306,0.028976,0.008330,-0.620479,venda
62,EQTL3,36.169998,13.154900,0.020899,0.013123,0.007776,-0.636304,venda
64,ENGI3,14.170000,9.666667,0.033179,0.015760,0.017419,-0.317808,venda
65,PSSA3,50.160000,31.998117,0.050887,0.031228,0.019659,-0.362079,venda
67,ALUP3,10.670000,4.948717,0.045422,0.029102,0.016320,-0.536203,venda

In [ ]:
resultado[resultado['recomendação'] == 'espera']

,ticker,preço,preço-alvo,yield,-1dp,dp,potencial,recomendação
0,VALE3,57.099998,75.962750,0.120261,0.057701,0.062560,0.330346,espera
1,PETR3,34.230000,87.297567,0.390117,0.033687,0.356430,1.550323,espera
2,BBAS3,22.230000,20.429050,0.079517,0.055366,0.024151,-0.081014,espera
3,BBDC4,16.889999,20.736483,0.066893,0.033532,0.033362,0.227737,espera
9,BEES3,8.190000,8.240900,0.090941,0.055610,0.035331,0.006215,espera
12,BGIP4,27.459999,49.763383,0.104137,0.037327,0.066809,0.812214,espera
13,BMEB4,49.410000,19.856033,0.074736,0.040987,0.033749,-0.598137,espera
14,BNBR3,99.989998,100.587700,0.070426,0.054211,0.016215,0.005978,espera
20,ITSA4,10.970000,17.777650,0.075626,0.051805,0.023821,0.620570,espera
23,VIVT3,33.419998,24.516367,0.072657,0.040024,0.032633,-0.266416,espera
26,CXSE3,13.950000,19.597867,0.083308,0.053195,0.030113,0.404865,espera
28,ISAE4,23.150000,33.445150,0.109375,0.057345,0.052030,0.444715,espera
31,SAPR3,7.660000,6.815950,0.064123,0.040756,0.023367,-0.110189,espera
34,WIZC3,8.190000,4.171983,0.077289,0.047389,0.029900,-0.490600,espera
35,VALE3,57.139999,75.962750,0.120261,0.057701,0.062560,0.329415,espera
36,PETR3,34.200001,87.297567,0.390117,0.033687,0.356430,1.552560,espera
37,BBAS3,22.299999,20.429050,0.079517,0.055366,0.024151,-0.083899,espera
38,BBDC4,16.879999,20.736483,0.066893,0.033532,0.033362,0.228465,espera
44,BEES3,8.200000,8.240900,0.090941,0.055610,0.035331,0.004988,espera
47,BGIP4,27.459999,49.763383,0.104137,0.037327,0.066809,0.812214,espera
48,BMEB4,49.570000,19.856033,0.074736,0.040987,0.033749,-0.599434,espera
49,BNBR3,99.989998,100.587700,0.070426,0.054211,0.016215,0.005978,espera
55,ITSA4,11.010000,17.777650,0.075626,0.051805,0.023821,0.614682,espera
58,VIVT3,33.560001,24.516367,0.072657,0.040024,0.032633,-0.269477,espera
61,CXSE3,13.990000,19.597867,0.083308,0.053195,0.030113,0.400848,espera
63,ISAE4,23.200001,33.445150,0.109375,0.057345,0.052030,0.441601,espera
66,SAPR3,7.690000,6.815950,0.064123,0.040756,0.023367,-0.113661,espera
69,WIZC3,8.230000,4.171983,0.077289,0.047389,0.029900,-0.493076,espera

In [ ]:
compras.to_excel('compras.xlsx')